// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;



/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKxzPtGQDArggGosRF-oxjxIZ49yX0DuE',
    appId: '1:565519577576:web:eb07ebb58ae7668558345d',
    messagingSenderId: '565519577576',
    projectId: 'sayer-app-e9af3',
    authDomain: 'sayer-app-e9af3.firebaseapp.com',
    storageBucket: 'sayer-app-e9af3.appspot.com',
    measurementId: 'G-L7CTG3BFL0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCduqWM74aoNrrsTlikpPaptVWHjvImEXs',
    appId: '1:565519577576:android:6cf96d89b21b324f58345d',
    messagingSenderId: '565519577576',
    projectId: 'sayer-app-e9af3',
    storageBucket: 'sayer-app-e9af3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWvRIUWLluw6vAIpFPUacKNPNbEve_PZk',
    appId: '1:565519577576:ios:488653831c83615658345d',
    messagingSenderId: '565519577576',
    projectId: 'sayer-app-e9af3',
    storageBucket: 'sayer-app-e9af3.appspot.com',
    iosBundleId: 'com.example.sayeer',
  );
}
